# Generated by Django 3.2.9 on 2022-05-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
                ('description', models.TextField(verbose_name='Сипаттама')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='receive_housing/', verbose_name='Сурет')),
            ],
            options={
                'verbose_name': 'Үй туралы мәлімет',
                'verbose_name_plural': 'Үй туралы мәліметтер',
                'db_table': 'homes',
            },
        ),
        migrations.CreateModel(
            name='Jer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
                ('description', models.TextField(verbose_name='Сипаттама')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='receive_jer_house/', verbose_name='Сурет')),
            ],
            options={
                'verbose_name': 'Жер туралы мәлімет',
                'verbose_name_plural': 'Жер туралы мәліметер',
                'db_table': 'zher',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Есімі')),
                ('text', models.TextField(max_length=5000, verbose_name='Хабарлама')),
                ('publish', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сұрақ',
                'verbose_name_plural': 'Сұрақтар',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Есімі')),
                ('surname', models.CharField(max_length=100, verbose_name='Тегі')),
                ('text', models.TextField(max_length=5000, verbose_name='Хабарлама')),
                ('image', models.ImageField(blank=True, upload_to='reviews/', verbose_name='Суреті')),
                ('publish', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пікір',
                'verbose_name_plural': 'Пікірлер',
                'db_table': 'reviews',
            },
        ),
    ]
