# Generated by Django 3.2.9 on 2022-05-24 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория аты')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
                'db_table': 'categorynews',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('description', models.TextField(verbose_name='Мәтіні')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Сурет')),
                ('slug', models.SlugField()),
                ('yout', models.CharField(max_length=2000, verbose_name='Жаңалыққа сілтеме')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жарияланған күні')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.categorynews', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Жаңалық',
                'verbose_name_plural': 'Жаңалықтар',
                'db_table': 'news',
            },
        ),
    ]
