# Generated by Django 3.2.9 on 2022-05-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_categorynews_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='yout',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Жаңалыққа сілтеме'),
        ),
    ]
