# Generated by Django 3.2.9 on 2022-05-28 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20220524_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='name',
        ),
        migrations.AddField(
            model_name='home',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Бағасы'),
        ),
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Титул'),
            preserve_default=False,
        ),
    ]
