# Generated by Django 3.2.9 on 2022-05-28 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20220528_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='Home_shots/', verbose_name='Изображение')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.home')),
            ],
            options={
                'verbose_name': 'Сурет',
                'verbose_name_plural': 'Суреттер',
                'db_table': 'images_home',
            },
        ),
    ]
