# Generated by Django 3.2.9 on 2022-05-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_homeshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Титул')),
                ('description', models.TextField(verbose_name='Сипаттама')),
            ],
            options={
                'verbose_name': 'Жалпы мәлімет',
                'verbose_name_plural': 'Жалпы мәліметер',
                'db_table': 'datasmodel',
            },
        ),
    ]
