# Generated by Django 3.2.9 on 2022-05-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_vakancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtinishVak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Есіміңіз')),
                ('surname', models.CharField(max_length=100, verbose_name='Тегіңіз')),
                ('nomer', models.CharField(max_length=11, verbose_name='Телефон номер')),
                ('email', models.EmailField(max_length=254)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('vakancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.vakancia', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Бос жұмыс орындарына өтініш',
                'verbose_name_plural': 'Бос жұмыс орындарына өтініштер',
                'db_table': 'otinishvak',
            },
        ),
    ]
