# Generated by Django 3.2.9 on 2022-05-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_otinishvak'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Есіміңіз')),
                ('surname', models.CharField(max_length=100, verbose_name='Тегіңіз')),
                ('nomer', models.CharField(max_length=11, verbose_name='Телефон номер')),
                ('req', models.CharField(choices=[('А', 'Ақшалай'), ('Ж', 'Жұмыс'), ('Ү', 'Үй'), ('Г', 'Гуманитарлық')], max_length=100, verbose_name='Көмек түрі')),
                ('email', models.EmailField(max_length=254)),
                ('publish', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Әлеуметтік көмек',
                'verbose_name_plural': 'Әлеуметтік көмектер',
                'db_table': 'requesthelp',
            },
        ),
    ]
