# Generated by Django 3.2.9 on 2022-05-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_requesthelp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthelp',
            name='req',
            field=models.CharField(choices=[('Ақшалай', 'Ақшалай'), ('Жұмыс', 'Жұмыс'), ('Үй', 'Үй'), ('Гуманитарлық', 'Гуманитарлық')], max_length=100, verbose_name='Көмек түрі'),
        ),
    ]
